<?php
/**
 * DestinyArtifactCharacterScoped
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.8.2
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model\Destiny\Artifacts;

use \ArrayAccess;
use \Bungie\ObjectSerializer;

/**
 * DestinyArtifactCharacterScoped Class Doc Comment
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyArtifactCharacterScoped implements \Bungie\Model\ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Destiny.Artifacts.DestinyArtifactCharacterScoped';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'artifactHash' => 'int',
        'pointsUsed' => 'int',
        'resetCount' => 'int',
        'tiers' => '\Bungie\Model\Destiny\Artifacts\DestinyArtifactTier[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'artifactHash' => 'uint32',
        'pointsUsed' => 'int32',
        'resetCount' => 'int32',
        'tiers' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'artifactHash' => 'artifactHash',
        'pointsUsed' => 'pointsUsed',
        'resetCount' => 'resetCount',
        'tiers' => 'tiers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'artifactHash' => 'setArtifactHash',
        'pointsUsed' => 'setPointsUsed',
        'resetCount' => 'setResetCount',
        'tiers' => 'setTiers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'artifactHash' => 'getArtifactHash',
        'pointsUsed' => 'getPointsUsed',
        'resetCount' => 'getResetCount',
        'tiers' => 'getTiers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['artifactHash'] = isset($data['artifactHash']) ? $data['artifactHash'] : null;
        $this->container['pointsUsed'] = isset($data['pointsUsed']) ? $data['pointsUsed'] : null;
        $this->container['resetCount'] = isset($data['resetCount']) ? $data['resetCount'] : null;
        $this->container['tiers'] = isset($data['tiers']) ? $data['tiers'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets artifactHash
     *
     * @return int|null
     */
    public function getArtifactHash()
    {
        return $this->container['artifactHash'];
    }

    /**
     * Sets artifactHash
     *
     * @param int|null $artifactHash artifactHash
     *
     * @return $this
     */
    public function setArtifactHash($artifactHash)
    {
        $this->container['artifactHash'] = $artifactHash;

        return $this;
    }

    /**
     * Gets pointsUsed
     *
     * @return int|null
     */
    public function getPointsUsed()
    {
        return $this->container['pointsUsed'];
    }

    /**
     * Sets pointsUsed
     *
     * @param int|null $pointsUsed pointsUsed
     *
     * @return $this
     */
    public function setPointsUsed($pointsUsed)
    {
        $this->container['pointsUsed'] = $pointsUsed;

        return $this;
    }

    /**
     * Gets resetCount
     *
     * @return int|null
     */
    public function getResetCount()
    {
        return $this->container['resetCount'];
    }

    /**
     * Sets resetCount
     *
     * @param int|null $resetCount resetCount
     *
     * @return $this
     */
    public function setResetCount($resetCount)
    {
        $this->container['resetCount'] = $resetCount;

        return $this;
    }

    /**
     * Gets tiers
     *
     * @return \Bungie\Model\Destiny\Artifacts\DestinyArtifactTier[]|null
     */
    public function getTiers()
    {
        return $this->container['tiers'];
    }

    /**
     * Sets tiers
     *
     * @param \Bungie\Model\Destiny\Artifacts\DestinyArtifactTier[]|null $tiers tiers
     *
     * @return $this
     */
    public function setTiers($tiers)
    {
        $this->container['tiers'] = $tiers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


