<?php
/**
 * DestinyReportOffensePgcrRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.6
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model\Destiny\Reporting\Requests;

use \ArrayAccess;
use \Bungie\ObjectSerializer;

/**
 * DestinyReportOffensePgcrRequest Class Doc Comment
 *
 * @category Class
 * @description If you want to report a player causing trouble in a game, this request will let you report that player and the specific PGCR in which the trouble was caused, along with why.  Please don&#39;t do this just because you dislike the person! I mean, I know people will do it anyways, but can you like take a good walk, or put a curse on them or something? Do me a solid and reconsider.  Note that this request object doesn&#39;t have the actual PGCR ID nor your Account/Character ID in it. We will infer that information from your authentication information and the PGCR ID that you pass into the URL of the reporting endpoint itself.
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyReportOffensePgcrRequest implements \Bungie\Model\ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Destiny.Reporting.Requests.DestinyReportOffensePgcrRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'reasonCategoryHashes' => 'int[]',
        'reasonHashes' => 'int[]',
        'offendingCharacterId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'reasonCategoryHashes' => 'uint32',
        'reasonHashes' => 'uint32',
        'offendingCharacterId' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reasonCategoryHashes' => 'reasonCategoryHashes',
        'reasonHashes' => 'reasonHashes',
        'offendingCharacterId' => 'offendingCharacterId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reasonCategoryHashes' => 'setReasonCategoryHashes',
        'reasonHashes' => 'setReasonHashes',
        'offendingCharacterId' => 'setOffendingCharacterId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reasonCategoryHashes' => 'getReasonCategoryHashes',
        'reasonHashes' => 'getReasonHashes',
        'offendingCharacterId' => 'getOffendingCharacterId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['reasonCategoryHashes'] = isset($data['reasonCategoryHashes']) ? $data['reasonCategoryHashes'] : null;
        $this->container['reasonHashes'] = isset($data['reasonHashes']) ? $data['reasonHashes'] : null;
        $this->container['offendingCharacterId'] = isset($data['offendingCharacterId']) ? $data['offendingCharacterId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reasonCategoryHashes
     *
     * @return int[]|null
     */
    public function getReasonCategoryHashes()
    {
        return $this->container['reasonCategoryHashes'];
    }

    /**
     * Sets reasonCategoryHashes
     *
     * @param int[]|null $reasonCategoryHashes So you've decided to report someone instead of cursing them and their descendants. Well, okay then. This is the category or categorie(s) of infractions for which you are reporting the user. These are hash identifiers that map to DestinyReportReasonCategoryDefinition entries.
     *
     * @return $this
     */
    public function setReasonCategoryHashes($reasonCategoryHashes)
    {
        $this->container['reasonCategoryHashes'] = $reasonCategoryHashes;

        return $this;
    }

    /**
     * Gets reasonHashes
     *
     * @return int[]|null
     */
    public function getReasonHashes()
    {
        return $this->container['reasonHashes'];
    }

    /**
     * Sets reasonHashes
     *
     * @param int[]|null $reasonHashes If applicable, provide a more specific reason(s) within the general category of problems provided by the reasonHash. This is also an identifier for a reason. All reasonHashes provided must be children of at least one the reasonCategoryHashes provided.
     *
     * @return $this
     */
    public function setReasonHashes($reasonHashes)
    {
        $this->container['reasonHashes'] = $reasonHashes;

        return $this;
    }

    /**
     * Gets offendingCharacterId
     *
     * @return int|null
     */
    public function getOffendingCharacterId()
    {
        return $this->container['offendingCharacterId'];
    }

    /**
     * Sets offendingCharacterId
     *
     * @param int|null $offendingCharacterId Within the PGCR provided when calling the Reporting endpoint, this should be the character ID of the user that you thought was violating terms of use. They must exist in the PGCR provided.
     *
     * @return $this
     */
    public function setOffendingCharacterId($offendingCharacterId)
    {
        $this->container['offendingCharacterId'] = $offendingCharacterId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


