<?php
/**
 * DestinySandboxPatternDefinition
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.17.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model\Destiny\Definitions;

use \ArrayAccess;
use \Bungie\ObjectSerializer;

/**
 * DestinySandboxPatternDefinition Class Doc Comment
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinySandboxPatternDefinition implements \Bungie\Model\ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Destiny.Definitions.DestinySandboxPatternDefinition';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'patternHash' => 'int',
        'patternGlobalTagIdHash' => 'int',
        'weaponContentGroupHash' => 'int',
        'weaponTranslationGroupHash' => 'int',
        'weaponTypeHash' => 'int',
        'weaponType' => 'int',
        'filters' => '\Bungie\Model\Destiny\Definitions\DestinyArrangementRegionFilterDefinition[]',
        'hash' => 'int',
        'index' => 'int',
        'redacted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'patternHash' => 'uint32',
        'patternGlobalTagIdHash' => 'uint32',
        'weaponContentGroupHash' => 'uint32',
        'weaponTranslationGroupHash' => 'uint32',
        'weaponTypeHash' => 'uint32',
        'weaponType' => 'int32',
        'filters' => null,
        'hash' => 'uint32',
        'index' => 'int32',
        'redacted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'patternHash' => 'patternHash',
        'patternGlobalTagIdHash' => 'patternGlobalTagIdHash',
        'weaponContentGroupHash' => 'weaponContentGroupHash',
        'weaponTranslationGroupHash' => 'weaponTranslationGroupHash',
        'weaponTypeHash' => 'weaponTypeHash',
        'weaponType' => 'weaponType',
        'filters' => 'filters',
        'hash' => 'hash',
        'index' => 'index',
        'redacted' => 'redacted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'patternHash' => 'setPatternHash',
        'patternGlobalTagIdHash' => 'setPatternGlobalTagIdHash',
        'weaponContentGroupHash' => 'setWeaponContentGroupHash',
        'weaponTranslationGroupHash' => 'setWeaponTranslationGroupHash',
        'weaponTypeHash' => 'setWeaponTypeHash',
        'weaponType' => 'setWeaponType',
        'filters' => 'setFilters',
        'hash' => 'setHash',
        'index' => 'setIndex',
        'redacted' => 'setRedacted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'patternHash' => 'getPatternHash',
        'patternGlobalTagIdHash' => 'getPatternGlobalTagIdHash',
        'weaponContentGroupHash' => 'getWeaponContentGroupHash',
        'weaponTranslationGroupHash' => 'getWeaponTranslationGroupHash',
        'weaponTypeHash' => 'getWeaponTypeHash',
        'weaponType' => 'getWeaponType',
        'filters' => 'getFilters',
        'hash' => 'getHash',
        'index' => 'getIndex',
        'redacted' => 'getRedacted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['patternHash'] = isset($data['patternHash']) ? $data['patternHash'] : null;
        $this->container['patternGlobalTagIdHash'] = isset($data['patternGlobalTagIdHash']) ? $data['patternGlobalTagIdHash'] : null;
        $this->container['weaponContentGroupHash'] = isset($data['weaponContentGroupHash']) ? $data['weaponContentGroupHash'] : null;
        $this->container['weaponTranslationGroupHash'] = isset($data['weaponTranslationGroupHash']) ? $data['weaponTranslationGroupHash'] : null;
        $this->container['weaponTypeHash'] = isset($data['weaponTypeHash']) ? $data['weaponTypeHash'] : null;
        $this->container['weaponType'] = isset($data['weaponType']) ? $data['weaponType'] : null;
        $this->container['filters'] = isset($data['filters']) ? $data['filters'] : null;
        $this->container['hash'] = isset($data['hash']) ? $data['hash'] : null;
        $this->container['index'] = isset($data['index']) ? $data['index'] : null;
        $this->container['redacted'] = isset($data['redacted']) ? $data['redacted'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets patternHash
     *
     * @return int|null
     */
    public function getPatternHash()
    {
        return $this->container['patternHash'];
    }

    /**
     * Sets patternHash
     *
     * @param int|null $patternHash patternHash
     *
     * @return $this
     */
    public function setPatternHash($patternHash)
    {
        $this->container['patternHash'] = $patternHash;

        return $this;
    }

    /**
     * Gets patternGlobalTagIdHash
     *
     * @return int|null
     */
    public function getPatternGlobalTagIdHash()
    {
        return $this->container['patternGlobalTagIdHash'];
    }

    /**
     * Sets patternGlobalTagIdHash
     *
     * @param int|null $patternGlobalTagIdHash patternGlobalTagIdHash
     *
     * @return $this
     */
    public function setPatternGlobalTagIdHash($patternGlobalTagIdHash)
    {
        $this->container['patternGlobalTagIdHash'] = $patternGlobalTagIdHash;

        return $this;
    }

    /**
     * Gets weaponContentGroupHash
     *
     * @return int|null
     */
    public function getWeaponContentGroupHash()
    {
        return $this->container['weaponContentGroupHash'];
    }

    /**
     * Sets weaponContentGroupHash
     *
     * @param int|null $weaponContentGroupHash weaponContentGroupHash
     *
     * @return $this
     */
    public function setWeaponContentGroupHash($weaponContentGroupHash)
    {
        $this->container['weaponContentGroupHash'] = $weaponContentGroupHash;

        return $this;
    }

    /**
     * Gets weaponTranslationGroupHash
     *
     * @return int|null
     */
    public function getWeaponTranslationGroupHash()
    {
        return $this->container['weaponTranslationGroupHash'];
    }

    /**
     * Sets weaponTranslationGroupHash
     *
     * @param int|null $weaponTranslationGroupHash weaponTranslationGroupHash
     *
     * @return $this
     */
    public function setWeaponTranslationGroupHash($weaponTranslationGroupHash)
    {
        $this->container['weaponTranslationGroupHash'] = $weaponTranslationGroupHash;

        return $this;
    }

    /**
     * Gets weaponTypeHash
     *
     * @return int|null
     */
    public function getWeaponTypeHash()
    {
        return $this->container['weaponTypeHash'];
    }

    /**
     * Sets weaponTypeHash
     *
     * @param int|null $weaponTypeHash weaponTypeHash
     *
     * @return $this
     */
    public function setWeaponTypeHash($weaponTypeHash)
    {
        $this->container['weaponTypeHash'] = $weaponTypeHash;

        return $this;
    }

    /**
     * Gets weaponType
     *
     * @return int|null
     */
    public function getWeaponType()
    {
        return $this->container['weaponType'];
    }

    /**
     * Sets weaponType
     *
     * @param int|null $weaponType weaponType
     *
     * @return $this
     */
    public function setWeaponType($weaponType)
    {
        $this->container['weaponType'] = $weaponType;

        return $this;
    }

    /**
     * Gets filters
     *
     * @return \Bungie\Model\Destiny\Definitions\DestinyArrangementRegionFilterDefinition[]|null
     */
    public function getFilters()
    {
        return $this->container['filters'];
    }

    /**
     * Sets filters
     *
     * @param \Bungie\Model\Destiny\Definitions\DestinyArrangementRegionFilterDefinition[]|null $filters filters
     *
     * @return $this
     */
    public function setFilters($filters)
    {
        $this->container['filters'] = $filters;

        return $this;
    }

    /**
     * Gets hash
     *
     * @return int|null
     */
    public function getHash()
    {
        return $this->container['hash'];
    }

    /**
     * Sets hash
     *
     * @param int|null $hash The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
     *
     * @return $this
     */
    public function setHash($hash)
    {
        $this->container['hash'] = $hash;

        return $this;
    }

    /**
     * Gets index
     *
     * @return int|null
     */
    public function getIndex()
    {
        return $this->container['index'];
    }

    /**
     * Sets index
     *
     * @param int|null $index The index of the entity as it was found in the investment tables.
     *
     * @return $this
     */
    public function setIndex($index)
    {
        $this->container['index'] = $index;

        return $this;
    }

    /**
     * Gets redacted
     *
     * @return bool|null
     */
    public function getRedacted()
    {
        return $this->container['redacted'];
    }

    /**
     * Sets redacted
     *
     * @param bool|null $redacted If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
     *
     * @return $this
     */
    public function setRedacted($redacted)
    {
        $this->container['redacted'] = $redacted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


