<?php
/**
 * DestinyDestinyCollectibleState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model;
use \Bungie\ObjectSerializer;

/**
 * DestinyDestinyCollectibleState Class Doc Comment
 *
 * @category Class
 * @description A Flags Enumeration where each bit represents a different state that the Collectible can be in. A collectible can be in any number of these states, and you can choose to use or ignore any or all of them when making your own UI that shows Collectible info. Our displays are going to honor them, but we&#39;re also the kind of people who only pretend to inhale before quickly passing it to the left. So, you know, do what you got to do.
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyDestinyCollectibleState
{
    /**
     * Possible values of this enum
     */
    const NONE = 0;
    const NOTACQUIRED = 1;
    const OBSCURED = 2;
    const INVISIBLE = 4;
    const CANNOTAFFORDMATERIALREQUIREMENTS = 8;
    const INVENTORYSPACEUNAVAILABLE = 16;
    const UNIQUENESSVIOLATION = 32;
    const PURCHASEDISABLED = 64;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::NOTACQUIRED,
            self::OBSCURED,
            self::INVISIBLE,
            self::CANNOTAFFORDMATERIALREQUIREMENTS,
            self::INVENTORYSPACEUNAVAILABLE,
            self::UNIQUENESSVIOLATION,
            self::PURCHASEDISABLED,
        ];
    }
}


