<?php
/**
 * ForumForumPostCategoryEnums
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model;
use \Bungie\ObjectSerializer;

/**
 * ForumForumPostCategoryEnums Class Doc Comment
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ForumForumPostCategoryEnums
{
    /**
     * Possible values of this enum
     */
    const NONE = 0;
    const TEXTONLY = 1;
    const MEDIA = 2;
    const LINK = 4;
    const POLL = 8;
    const QUESTION = 16;
    const ANSWERED = 32;
    const ANNOUNCEMENT = 64;
    const CONTENTCOMMENT = 128;
    const BUNGIEOFFICIAL = 256;
    const NINJAOFFICIAL = 512;
    const RECRUITMENT = 1024;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::TEXTONLY,
            self::MEDIA,
            self::LINK,
            self::POLL,
            self::QUESTION,
            self::ANSWERED,
            self::ANNOUNCEMENT,
            self::CONTENTCOMMENT,
            self::BUNGIEOFFICIAL,
            self::NINJAOFFICIAL,
            self::RECRUITMENT,
        ];
    }
}


