<?php
/**
 * DestinyItemSortType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.5
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model\Destiny;
use \Bungie\ObjectSerializer;

/**
 * DestinyItemSortType Class Doc Comment
 *
 * @category Class
 * @description Determines how items are sorted in an inventory bucket.
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyItemSortType
{
    /**
     * Possible values of this enum
     */
    const DESTINY_ITEM_SORT_TYPE_ITEMID = 0;
    const DESTINY_ITEM_SORT_TYPE_TIMESTAMP = 1;
    const DESTINY_ITEM_SORT_TYPE_STACKSIZE = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_ITEM_SORT_TYPE_ITEMID,
            self::DESTINY_ITEM_SORT_TYPE_TIMESTAMP,
            self::DESTINY_ITEM_SORT_TYPE_STACKSIZE,
        ];
    }
}


