<?php
/**
 * DestinyCollectibleDefinition
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.4
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model\Destiny\Definitions\Collectibles;

use \ArrayAccess;
use \Bungie\ObjectSerializer;

/**
 * DestinyCollectibleDefinition Class Doc Comment
 *
 * @category Class
 * @description Defines a
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyCollectibleDefinition implements \Bungie\Model\ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Destiny.Definitions.Collectibles.DestinyCollectibleDefinition';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'displayProperties' => '\Bungie\Model\Destiny\Definitions\Common\DestinyDisplayPropertiesDefinition',
        'scope' => 'int',
        'sourceString' => 'string',
        'sourceHash' => 'int',
        'itemHash' => 'int',
        'acquisitionInfo' => '\Bungie\Model\Destiny\Definitions\Collectibles\DestinyCollectibleAcquisitionBlock',
        'stateInfo' => '\Bungie\Model\Destiny\Definitions\Collectibles\DestinyCollectibleStateBlock',
        'presentationInfo' => '\Bungie\Model\Destiny\Definitions\Presentation\DestinyPresentationChildBlock',
        'hash' => 'int',
        'index' => 'int',
        'redacted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'displayProperties' => null,
        'scope' => 'int32',
        'sourceString' => null,
        'sourceHash' => 'uint32',
        'itemHash' => 'uint32',
        'acquisitionInfo' => null,
        'stateInfo' => null,
        'presentationInfo' => null,
        'hash' => 'uint32',
        'index' => 'int32',
        'redacted' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'displayProperties' => 'displayProperties',
        'scope' => 'scope',
        'sourceString' => 'sourceString',
        'sourceHash' => 'sourceHash',
        'itemHash' => 'itemHash',
        'acquisitionInfo' => 'acquisitionInfo',
        'stateInfo' => 'stateInfo',
        'presentationInfo' => 'presentationInfo',
        'hash' => 'hash',
        'index' => 'index',
        'redacted' => 'redacted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'displayProperties' => 'setDisplayProperties',
        'scope' => 'setScope',
        'sourceString' => 'setSourceString',
        'sourceHash' => 'setSourceHash',
        'itemHash' => 'setItemHash',
        'acquisitionInfo' => 'setAcquisitionInfo',
        'stateInfo' => 'setStateInfo',
        'presentationInfo' => 'setPresentationInfo',
        'hash' => 'setHash',
        'index' => 'setIndex',
        'redacted' => 'setRedacted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'displayProperties' => 'getDisplayProperties',
        'scope' => 'getScope',
        'sourceString' => 'getSourceString',
        'sourceHash' => 'getSourceHash',
        'itemHash' => 'getItemHash',
        'acquisitionInfo' => 'getAcquisitionInfo',
        'stateInfo' => 'getStateInfo',
        'presentationInfo' => 'getPresentationInfo',
        'hash' => 'getHash',
        'index' => 'getIndex',
        'redacted' => 'getRedacted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['displayProperties'] = isset($data['displayProperties']) ? $data['displayProperties'] : null;
        $this->container['scope'] = isset($data['scope']) ? $data['scope'] : null;
        $this->container['sourceString'] = isset($data['sourceString']) ? $data['sourceString'] : null;
        $this->container['sourceHash'] = isset($data['sourceHash']) ? $data['sourceHash'] : null;
        $this->container['itemHash'] = isset($data['itemHash']) ? $data['itemHash'] : null;
        $this->container['acquisitionInfo'] = isset($data['acquisitionInfo']) ? $data['acquisitionInfo'] : null;
        $this->container['stateInfo'] = isset($data['stateInfo']) ? $data['stateInfo'] : null;
        $this->container['presentationInfo'] = isset($data['presentationInfo']) ? $data['presentationInfo'] : null;
        $this->container['hash'] = isset($data['hash']) ? $data['hash'] : null;
        $this->container['index'] = isset($data['index']) ? $data['index'] : null;
        $this->container['redacted'] = isset($data['redacted']) ? $data['redacted'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets displayProperties
     *
     * @return \Bungie\Model\Destiny\Definitions\Common\DestinyDisplayPropertiesDefinition|null
     */
    public function getDisplayProperties()
    {
        return $this->container['displayProperties'];
    }

    /**
     * Sets displayProperties
     *
     * @param \Bungie\Model\Destiny\Definitions\Common\DestinyDisplayPropertiesDefinition|null $displayProperties displayProperties
     *
     * @return $this
     */
    public function setDisplayProperties($displayProperties)
    {
        $this->container['displayProperties'] = $displayProperties;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return int|null
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param int|null $scope Indicates whether this Collectible's state is determined on a per-character or on an account-wide basis.
     *
     * @return $this
     */
    public function setScope($scope)
    {
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets sourceString
     *
     * @return string|null
     */
    public function getSourceString()
    {
        return $this->container['sourceString'];
    }

    /**
     * Sets sourceString
     *
     * @param string|null $sourceString A human readable string for a hint about how to acquire the item.
     *
     * @return $this
     */
    public function setSourceString($sourceString)
    {
        $this->container['sourceString'] = $sourceString;

        return $this;
    }

    /**
     * Gets sourceHash
     *
     * @return int|null
     */
    public function getSourceHash()
    {
        return $this->container['sourceHash'];
    }

    /**
     * Sets sourceHash
     *
     * @param int|null $sourceHash This is a hash identifier we are building on the BNet side in an attempt to let people group collectibles by similar sources.  I can't promise that it's going to be 100% accurate, but if the designers were consistent in assigning the same source strings to items with the same sources, it *ought to* be. No promises though.  This hash also doesn't relate to an actual definition, just to note: we've got nothing useful other than the source string for this data.
     *
     * @return $this
     */
    public function setSourceHash($sourceHash)
    {
        $this->container['sourceHash'] = $sourceHash;

        return $this;
    }

    /**
     * Gets itemHash
     *
     * @return int|null
     */
    public function getItemHash()
    {
        return $this->container['itemHash'];
    }

    /**
     * Sets itemHash
     *
     * @param int|null $itemHash itemHash
     *
     * @return $this
     */
    public function setItemHash($itemHash)
    {
        $this->container['itemHash'] = $itemHash;

        return $this;
    }

    /**
     * Gets acquisitionInfo
     *
     * @return \Bungie\Model\Destiny\Definitions\Collectibles\DestinyCollectibleAcquisitionBlock|null
     */
    public function getAcquisitionInfo()
    {
        return $this->container['acquisitionInfo'];
    }

    /**
     * Sets acquisitionInfo
     *
     * @param \Bungie\Model\Destiny\Definitions\Collectibles\DestinyCollectibleAcquisitionBlock|null $acquisitionInfo acquisitionInfo
     *
     * @return $this
     */
    public function setAcquisitionInfo($acquisitionInfo)
    {
        $this->container['acquisitionInfo'] = $acquisitionInfo;

        return $this;
    }

    /**
     * Gets stateInfo
     *
     * @return \Bungie\Model\Destiny\Definitions\Collectibles\DestinyCollectibleStateBlock|null
     */
    public function getStateInfo()
    {
        return $this->container['stateInfo'];
    }

    /**
     * Sets stateInfo
     *
     * @param \Bungie\Model\Destiny\Definitions\Collectibles\DestinyCollectibleStateBlock|null $stateInfo stateInfo
     *
     * @return $this
     */
    public function setStateInfo($stateInfo)
    {
        $this->container['stateInfo'] = $stateInfo;

        return $this;
    }

    /**
     * Gets presentationInfo
     *
     * @return \Bungie\Model\Destiny\Definitions\Presentation\DestinyPresentationChildBlock|null
     */
    public function getPresentationInfo()
    {
        return $this->container['presentationInfo'];
    }

    /**
     * Sets presentationInfo
     *
     * @param \Bungie\Model\Destiny\Definitions\Presentation\DestinyPresentationChildBlock|null $presentationInfo presentationInfo
     *
     * @return $this
     */
    public function setPresentationInfo($presentationInfo)
    {
        $this->container['presentationInfo'] = $presentationInfo;

        return $this;
    }

    /**
     * Gets hash
     *
     * @return int|null
     */
    public function getHash()
    {
        return $this->container['hash'];
    }

    /**
     * Sets hash
     *
     * @param int|null $hash The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
     *
     * @return $this
     */
    public function setHash($hash)
    {
        $this->container['hash'] = $hash;

        return $this;
    }

    /**
     * Gets index
     *
     * @return int|null
     */
    public function getIndex()
    {
        return $this->container['index'];
    }

    /**
     * Sets index
     *
     * @param int|null $index The index of the entity as it was found in the investment tables.
     *
     * @return $this
     */
    public function setIndex($index)
    {
        $this->container['index'] = $index;

        return $this;
    }

    /**
     * Gets redacted
     *
     * @return bool|null
     */
    public function getRedacted()
    {
        return $this->container['redacted'];
    }

    /**
     * Sets redacted
     *
     * @param bool|null $redacted If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
     *
     * @return $this
     */
    public function setRedacted($redacted)
    {
        $this->container['redacted'] = $redacted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


