<?php
/**
 * DeveloperRole
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\Model\Applications;
use \Bungie\ObjectSerializer;

/**
 * DeveloperRole Class Doc Comment
 *
 * @category Class
 * @package  Bungie
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeveloperRole
{
    /**
     * Possible values of this enum
     */
    const DEVELOPER_ROLE_NONE = 0;
    const DEVELOPER_ROLE_OWNER = 1;
    const DEVELOPER_ROLE_TEAMMEMBER = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DEVELOPER_ROLE_NONE,
            self::DEVELOPER_ROLE_OWNER,
            self::DEVELOPER_ROLE_TEAMMEMBER,
        ];
    }
}


